### ISSUE TITLE
08_greedy_algorithms/python/01_set_covering.py

### ISSUE THREAD

**Issue by T-CHARE** [egonSchiele/grokking_algorithms#115]
......
  for station, states in stations.items():
    _**covered = (states_needed & states)**_
    if len(covered) > len(states_covered):
      best_station = station
      states_covered = covered
......

should be like this:

......
  for station, states in stations.items():
    **_covered = (states_needed & states).union(states)_**
    if len(covered) > len(states_covered):
      best_station = station
      states_covered = covered
......

**Comment by egonSchiele** [comment]
fixed
