### ISSUE TITLE
answer to question # 2.2

### ISSUE THREAD

**Issue by rahulaga-msft** [egonSchiele/grokking_algorithms#117]
Answer to question 2.2 says - **A linked list** because _Lots of inserts are happening (servers 
adding orders), which linked lists excel at. You don’t need search 
or random access (what arrays excel at), because the chefs always 
take the first order off the queue._

Isn't in queue insert always happens at last and array would be better choice ? 

Or this answer is driven by considering factor - "what if required space is not available in existing contiguous block ? "

**Comment by egonSchiele** [comment]
Hey Rahul, even if an insert is happening at the end, we can store a pointer to the end, so we don't need to traverse the entire linked list to insert an item. In the future, for questions like this, please feel free to email me and I'll be quicker to respond.
