### ISSUE TITLE
7.1_C Answer - 4

### ISSUE THREAD

**Issue by nazjude** [egonSchiele/grokking_algorithms#158]
Hi, thanks for this great work,

Yes, negative weighted edge there in 7.1 C graph, but no negative cycle, right?

Thus we do have a shortest path from start to finish, whose weight is 4, true?

![Screenshot 2020-01-30 at 1 23 07 PM](https://user-images.githubusercontent.com/51318229/73422359-b2def180-4363-11ea-8617-559fbb14cf08.png)

**Comment by nazjude** [comment]
test code below:

#lvl 0
graph = {}
graph["start"] = {}
graph["start"]["a"] = 2
graph["start"]["c"] = 2
#1
graph["a"] = {}
graph["c"] = {}
graph["a"]["fin"] = 2
graph["a"]["b"] = 2
graph["c"]["a"] = 2
#2
graph["b"] = {}
graph["fin"] = {}
graph["b"]["fin"] = 2
graph["b"]["c"] = -1

#costs from start to nodes
infinity = float("inf")
costs = {}
costs["a"] = 2
costs["c"] = 2
costs["b"] = infinity
costs["fin"] = infinity

#tracking parents is tracking route
parents = {}
parents["a"] = "start"
parents["c"] = "start"
parents["b"] = None
parents["fin"] = None

checked = []
#process each in costs
def findLowestCostNode(costs):
    lowestCost = float("inf")
    lowestNode = None
    for each in costs:
        cost = costs[each]
        if lowestCost > cost and each not in checked:
            lowestCost = cost
            lowestNode = each
    if lowestNode is not None:
        print("To <" + lowestNode + "> ")
    return lowestNode
#srch node by node
def DijkstraSrch():
    node = findLowestCostNode(costs)
    while node is not None:
        neighbours = graph[node].keys()
        for each in neighbours:
            cost = costs[node] + graph[node][each]
            if costs[each] > cost:
                costs[each] = cost
                parents[each] = node
                str = "".join(parents[each] + " -> " + each)
                print("update " + str)
        checked.append(node)
        node = findLowestCostNode(costs)
    print("check sequence:")
    return checked

print(DijkstraSrch())
print("cost updatd: ")
print(costs)

**Comment by nazjude** [comment]
test code attached:
[7.1_C.txt](https://github.com/egonSchiele/grokking_algorithms/files/4132404/7.1_C.txt)

version:
>>> print(sys.version)
3.7.6 (default, Jan  8 2020, 20:19:54) 

results:
To <a> 
update a -> b
update a -> fin
To <c> 
To <b> 
To <fin> 
check sequence:
['a', 'c', 'b', 'fin']
cost updatd: 
{'a': 2, 'c': 2, 'b': 4, 'fin': 4}

**Comment by egonSchiele** [comment]
correct, this should now be fixed
