### ISSUE TITLE
Problem regarding Dijkstra's algorithm with changed values

### ISSUE THREAD

**Issue by sleipnir029** [egonSchiele/grokking_algorithms#166]
For the given graph, when I changed the values of **A** and **B**, where `A < B`. I don't get the desired path. 
Here's the [link](https://github.com/sleipnir029/grokkin-algorithms/blob/master/Chapter7.ipynb) to the code. I have checked for negative-weight edges and found none. I have also implemented a function that shows the final path.

Result for the given graph:
![firstprint](https://user-images.githubusercontent.com/52344836/82501553-43119400-9b17-11ea-9283-200bf8813e05.PNG)

Result with changed values
![secondprint](https://user-images.githubusercontent.com/52344836/82501596-515fb000-9b17-11ea-9bd8-db179737f613.PNG)

**Comment by egonSchiele** [comment]
Hey there, sorry for my very late response. Since this issue is old, I'm assuming you got it figured out, but let me know if you did not.
