### ISSUE TITLE
Binary Search in Java is not working properly without sorting it first. 

### ISSUE THREAD

**Issue by ghost** [egonSchiele/grokking_algorithms#177]
public class BinarySearch {
    public static void main(String[] args) {
        int[] myList = {87, 21, 45, 93};
        
       //add this line  Arrays.sort(myList);
        System.out.println(binarySearch(myList, 93));
     
I might be wrong, I am just a newbie

**Comment by egonSchiele** [comment]
Hi there, sorry for my very late response, I'd like to keep the code to just binary search, but you're welcome to open a PR that adds a comment saying that the array needs to be sorted first.
