### ISSUE TITLE
Typo in load factor (Chapter #5 hash tables)

### ISSUE THREAD

**Issue by alewis729** [egonSchiele/grokking_algorithms#198]
## Description

Hey, I wanted to point out that I found a discrepancy on the recommended time to resize a hash table. The images are from chapter 5 Hash tables, pages 92 & 94.

I'm guessing that in page 94, the highlighted load factor should also be `0.7` instead of `.07`.

![image](https://user-images.githubusercontent.com/51219653/115128875-88984480-9fa6-11eb-89bf-04192108f920.png)

![image](https://user-images.githubusercontent.com/51219653/115128885-96e66080-9fa6-11eb-9b44-1af375dfff4e.png)

Thanks for the amazing work on the book btw! I'm really loving how well concepts are explained.

**Comment by egonSchiele** [comment]
Hi there, sorry for my very late response. I'll add this to the errata page. I'm glad you liked the book! In the future, please feel free to email me as I'm much quicker at responding to those.
