### ISSUE TITLE
selection sort implementation 

### ISSUE THREAD

**Issue by mn3m-cs** [egonSchiele/grokking_algorithms#199]
selection sort should be **in-place**, why you create an additional array to keep sorted elements in it?

**Comment by pfrontera** [comment]
I just created a PR about this tòpic. With this implementation, sorting is in-place swapping the values inside the same array.

**Comment by pfrontera** [comment]
Hi @egonSchiele I made this implementation after reading and learning from your book. Do you have any suggestions about the PR I did?

**Comment by egonSchiele** [comment]
merged
