### ISSUE TITLE
grokking_algorithms/01_introduction_to_algorithms/java/01_binary_search/src/main/BinarySearch.java

### ISSUE THREAD

**Issue by veiuper** [egonSchiele/grokking_algorithms#217]
int[] myList = {87, 21, 45, 93};
The array is not sorted.
Must be:
int[] myList = {21, 45, 87, 93};

**Comment by veiuper** [comment]
System.out.println(binarySearch(myList, 87));

This line will work incorrectly.

**Comment by To-heeb** [comment]
I also noticed this and was about to create an issue for it.

**Comment by aneeshmohan0** [comment]
I have created one. :( 
I can open merge request if that helps.
