### ISSUE TITLE
Understanding Quick Sort Algorithm

### ISSUE THREAD

**Issue by carpet92** [egonSchiele/grokking_algorithms#22]
Thanks for this great work on algorithms book. I now understand many of concepts which seemed difficult to me but now I'm stuck on Quick Sort algorithm and I cannot fully understand how its work.

JavaScript Version of Code (from repository):

```javascript
function quicksort(array) {
    if (array.length < 2) {
        // base case, arrays with 0 or 1 element are already "sorted"
        return array
    } else {
        // recursive case
        let pivot = array[0]

        // sub-array of all the elements less than the pivot
        let less = array.slice(1).filter(function(el) {
            return el <= pivot
        })

        // sub-array of all the elements greater than the pivot
        let greater = array.slice(1).filter(function(el) {
            return el > pivot
        })

        return quicksort(less).concat([pivot], quicksort(greater))
    }
}
```

How I understanding parts of work this algorithm:

```
console.log(quicksort([10, 5, 2, 3]))
```

first step:

```
quicksort([10, 5, 2, 3])
pivot = 10 // get first item from array[0]
less = [5, 2, 3] // list of all item less than pivot
greater = [] // no items greater than pivot
quicksort([5, 2, 3]).concat([10], quicksort([]))
```

![untitled - copy 2](https://user-images.githubusercontent.com/20873402/28245701-b86d7816-69c1-11e7-9445-c7d8c424d320.png)

now we save this step ☝️ in stack and adding new step to up of stack 👇:

```
quicksort([5, 2, 3])
pivot = 5
less = [2, 3]
greater = []
quicksort([2, 3]).concat([5], quicksort([]))
```

![untitled](https://user-images.githubusercontent.com/20873402/28245650-afb6004a-69c0-11e7-80e4-5cdcdad75434.png)

and last step:

```
quicksort([2, 3])
pivot = 2
less = []
greater = [3]
quicksort([]).concat([2], quicksort([3]))
```

![untitledasdsad](https://user-images.githubusercontent.com/20873402/28245684-683ed8f8-69c1-11e7-89d6-90c6bdd295b3.png)

AND now the part I'm not sure I understand correctly:

now we concat array down to up i.e.:

```
[] + [2] + [3] + [5] + [10]
```

Why it's confusing for me? Because In "Recursion" chapter says that stack runs from up to down like on following screenshot:

![16-07-2017 00-02-30](https://user-images.githubusercontent.com/20873402/28245449-afb07f3a-69bb-11e7-85e9-a8d8feffd8d6.png)

also on last part:

```
quicksort([]).concat([2], quicksort([3]))
```

when quicksort function gets array `[3]`:

```
quicksort([3])
```

but since base case return true `if (array.length < 2) { return array }` we just return `[3]` array and code stop working.

![last](https://user-images.githubusercontent.com/20873402/28245767-767aed5c-69c2-11e7-9d11-fb6e3655d18d.png)

What happens on this part?

Can anyone help me to understand where I made a mistake in my explanations? What am I wrong about?

**Comment by oleg-gf** [comment]
I mean, the case { return array } happens after quicksort([]).concat([2], quicksort([3])), and we have [ 2, 3 ] and [5], [10] in stack that joined to [ 2, 3 ] when function does last return.

**Comment by Zx-EvM** [comment]
@oleg-gf hm. so, we have stack work from top to down. like on my last screen?! thanks.

**Comment by oleg-gf** [comment]
Yes, First Input Last Output.

**Comment by egonSchiele** [comment]
Hey there, it looks like this question was resolved, but please feel free to email me if you have more questions.
