### ISSUE TITLE
Dijkstra Algorithm Golang Issue

### ISSUE THREAD

**Issue by BrianMwangi21** [egonSchiele/grokking_algorithms#233]
Hi guys, I am trying to run the Golang implementation on the graph below and the cost to the stop is the MaxInt set in the beginning.

```golang
	graph["start"] = map[string]int{}
	graph["start"]["b"] = 5
	graph["start"]["c"] = 2

	graph["b"] = map[string]int{}
	graph["b"]["d"] = 1
	graph["b"]["e"] = 4

	graph["c"] = map[string]int{}
	graph["c"]["b"] = 8
	graph["c"]["d"] = 7

	graph["d"] = map[string]int{}
	graph["d"]["stop"] = 1

	graph["e"] = map[string]int{}
	graph["e"]["d"] = 6
	graph["e"]["stop"] = 3
	
	graph["stop"] = map[string]int{}
```

I have added the following lines in the implementation  while looping through the nodes of the lowestCostNode and it seems to now be working but I am not certain if that's the best approach or otherwise.

```golang
		for lowestCostNode != "" {
		for node, cost := range graph[lowestCostNode] {
			// The following three lines have been added
			if _, isSet := costs[node]; !isSet {
				costs[node] = cost
			}
			
			newCost := costs[lowestCostNode] + cost

			if newCost < costs[node] {
				costs[node] = newCost
				parents[node] = lowestCostNode
			}
		}

		processed[lowestCostNode] = true
		lowestCostNode = findLowestCostNode(costs, processed)
	}
```

**Comment by BrianMwangi21** [comment]
You can find my full implementation here together with the tests : https://github.com/BrianMwangi21/grokking-algos/tree/main/dijkstra

**Comment by egonSchiele** [comment]
Hi there! Sorry it took me so long to get to this issue. Since it's been a while and the Go code has received some updates, take a look and see if that solves your issue.
