### ISSUE TITLE
Hacktoberfest Inclusion

### ISSUE THREAD

**Issue by Sylk** [egonSchiele/grokking_algorithms#239]
Can you add the topic of Hacktoberfest, as I'm aiming to supply a few solutions for some languages that aren't fully covered in this book.

**Comment by egonSchiele** [comment]
Hey, sorry for my late response on this. In the future, please go ahead and open PRs as I'm quicker to respond to those (although I'm pretty slow at responding to both).

**Comment by Sylk** [comment]
Hah, 2 years and 2 months later! Well glad to see you toss it on there.
