### ISSUE TITLE
Java Chapter 1

### ISSUE THREAD

**Issue by aneeshmohan0** [egonSchiele/grokking_algorithms#282]
In BinarySearch.java 
Since the array myList is unsorted, the binary search algorithm may not produce the correct result. While the algorithm might still run without errors, the output cannot be guaranteed to be accurate because it's searching in an unsorted context.

If you provide me permission I will open the Merge Request for the bug.

**Comment by egonSchiele** [comment]
Hey Mohan, I'd like to keep the code to just binary search in that file, but you're welcome to open a PR with a comment explaining that the array needs to be sorted
