### ISSUE TITLE
Python 2 -> Python 3 .  Should I rewrite all the algorithms in Python 3 ?

### ISSUE THREAD

**Issue by ramitmittal** [egonSchiele/grokking_algorithms#40]
Should i rewrite all the algorithms in Python 3 ?
Suggestions ?

**Comment by Matanley** [comment]
Now there are a lot people who are still using Python 2.x and have no problem stay with it. I think we better keep the original python 2 codes but rewrite python 3 codes in seperate files include them in the same directory so it will be easier for others to choose. #53
