### ISSUE TITLE
We need complete sample code for Chapter 9, 10, 11

### ISSUE THREAD

**Issue by binbjz** [egonSchiele/grokking_algorithms#69]
For Charpter 9, 10, 11, Why not provide complete sample code ? For example, Longest common substring, K nearest neighbor algorithm. I really need them !

**Comment by egonSchiele** [comment]
@binbjz check out https://github.com/egonSchiele/grokking_algorithms/tree/master/10_knn

**Comment by binbjz** [comment]
> @binbjz check out https://github.com/egonSchiele/grokking_algorithms/tree/master/10_knn

Hi egonSchiele. For Charpter 9, 10, 11, I think we need complete sample code with python. This will be very important for us. Looking forward to your check-in
