### ISSUE TITLE
Missing division in the binary search (in the book)

### ISSUE THREAD

**Issue by lincolnfrias** [egonSchiele/grokking_algorithms#7]
Hi,

in p. 9 of the book (when you show the binary search algorithm), there is no division after  `mid = (low + high)`.

Congrats for the wonderful book!

**Comment by egonSchiele** [comment]
@lincolnfrias,
I'm glad you are enjoying the book! This one has been added to the errata page already (http://adit.io/errata.html), but please report any other issues you find. This is a fine way to report issues.
