### ISSUE TITLE
Typo in python selection sort

### ISSUE THREAD

**Issue by whatisnormal** [egonSchiele/grokking_algorithms#70]
Hi,
Current
`    if arr[i] < smallest:
         smallest_index = I
`

should be 

`    if arr[i] < smallest:
          smallest_index = i
          smallest = arr[i]
`

**Comment by ramitmittal** [comment]
@B3y0nd3r I couldn't find **capital I** in 01_selection_sort.py

**Comment by B3y0nd3r** [comment]
Hi @ramitmittal , the capital I was a typo sorry.
We should have the "bold" line also can you please confirm? Otherwise "smallest" will always be the initial value arr[0]

if arr[i] < smallest: 
     smallest_index = i
     **smallest = arr[i]**

**Comment by ramitmittal** [comment]
solved in accepted pull request #72 , please close this issue
